Teach mypy XyzAddress is a subtype of Address
This commit teaches mypy InitiatorAddress is a subtype of Address.
This is a tiny bite on #3040.

Before this commit, when I ran mypy, I got an error message saying
an InitiatorAddress cannot be used as an Address.
```
mypy raiden/transfer/mediated_transfer/target.py --ignore-missing-imports
raiden/transfer/mediated_transfer/target.py:100: error: Argument "recipient" to "SendSecretRequest" has incompatible type "InitiatorAddress"; expected "Address"
```

After this commit, these errors disappear without any additional
errors.